pragma solidity ^0.4.24;
// Define a contract 'Supplychain'
import "../bakeryaccesscontrol/BakerRole.sol";
import "../bakeryaccesscontrol/ConsumerRole.sol";
import "../bakeryaccesscontrol/DeliveryAgentRole.sol";
import "../coffeecore/Ownable.sol";

  contract SupplyChain is BakerRole, ConsumerRole, DeliveryAgentRole{

  // Define 'owner'
  address owner;

  // Define a variable called 'upc' for Universal Product Code (UPC)
  uint  upc;

  // Define a variable called 'sku' for Stock Keeping Unit (SKU)
  uint  sku;

  // Define a public mapping 'items' that maps the UPC to an Item.
  mapping (uint => Item) items;

  // Define a public mapping 'itemsHistory' that maps the UPC to an array of TxHash, 
  // that   its journey through the supply chain -- to be sent from DApp.
  mapping (uint => string[]) itemsHistory;
  
  // Define enum 'State' with the following values:
  enum State 
  { 
    Baked,      // 0
    ForSale,    // 1
    Sold,       // 2
    Shipped,    // 3
    Delivered,  // 4
    Received   // 5
    
    }

  State constant defaultState = State.Baked;

  // Define a struct 'Item' with the following fields:
  struct Item {
    uint    sku;  // Stock Keeping Unit (SKU)
    uint    upc; // Universal Product Code (UPC), generated by the Farmer, goes on the package, can be verified by the Consumer
    address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through 8 stages
    address originBakerID; // Metamask-Ethereum address of the Farmer
    string  originBakerName; // Farmer Name
    string  originBakerInformation;  // Farmer Information
    uint    productID;  // Product ID potentially a combination of upc + sku
    string  productNotes; // Product Notes
    uint    productPrice; // Product Price
    State   itemState;  // Product State as represented in the enum above
    address deliveryAgentID;  // Metamask-Ethereum address of the Distributor
    address consumerID; // Metamask-Ethereum address of the Consumer
  }

  // Define 4 events with the same 4 state values and accept 'upc' as input argument
     event Baked(uint upc);
   event ForSale(uint upc);
  event Sold(uint upc);
  event Shipped(uint upc);
  event Delivered(uint upc);
  event Received(uint upc);
 
  // Define a modifer that checks to see if msg.sender == owner of the contract
  modifier onlyOwner() {
    require(msg.sender == owner);
    _;
  }

  // Define a modifer that verifies the Caller
  modifier verifyCaller (address _address) {
    require(msg.sender == _address); 
     
    _;
  }

  // Define a modifier that checks if the paid amount is sufficient to cover the price
  modifier paidEnough(uint _price) { 
    require(msg.value >= _price); 
    _;
  }
  
  // Define a modifier that checks the price and refunds the remaining balance
  modifier checkValue(uint _upc) {
    _;
    uint _price = items[_upc].productPrice;
    uint amountToReturn = msg.value - _price;
    items[_upc].consumerID.transfer(amountToReturn);
  }

 
 

  // Define a modifier that checks if an item.state of a upc is ForSale
  modifier baked(uint _upc) {
    require(items[_upc].itemState == State.Baked);

    _;
  }
 

  // Define a modifier that checks if an item.state of a upc is ForSale
  modifier forSale(uint _upc) {
    require(items[_upc].itemState == State.ForSale);

    _;
  }

  // Define a modifier that checks if an item.state of a upc is Sold
  modifier sold(uint _upc) {
    require(items[_upc].itemState == State.Sold);
    _;
  }
  
  // Define a modifier that checks if an item.state of a upc is Shipped
  modifier shipped(uint _upc) {
    require(items[_upc].itemState == State.Shipped);

    _;
  }

  // Define a modifier that checks if an item.state of a upc is delivered
  modifier delivered(uint _upc) {
    require(items[_upc].itemState == State.Delivered);

    _;
  }
  // Define a modifier that checks if an item.state of a upc is Received
  modifier received(uint _upc) {
    require(items[_upc].itemState == State.Received);

    _;
  }

  

  // In the constructor set 'owner' to the address that instantiated the contract
  // and set 'sku' to 1
  // and set 'upc' to 1
  constructor() public payable {
    owner = msg.sender;
    sku = 1;
    upc = 1;
  }

  // Define a function 'kill' if required
  function kill() public {
    if (msg.sender == owner) {
      selfdestruct(owner);
    }
  }

  // Define a function 'bakeCookies' that allows a farmer to mark an item 'Harvested'
  function bakeCookies(uint _upc, address _originBakerID, string _originBakerName, string _originBakerInformation, string  _productNotes, uint _productPrice) onlyBaker()  public {
// Add the new item  
    items[_upc] = Item({
      sku: sku,
      upc: _upc,
      ownerID: _originBakerID,
      productID: sku + _upc ,
      originBakerID: _originBakerID,
      originBakerName: _originBakerName,
      originBakerInformation: _originBakerInformation ,
      productNotes: _productNotes,
      itemState: State.Baked,
      productPrice: _productPrice,
      deliveryAgentID:address(0),
      consumerID: address(0)
       });

       // Increment sku
    sku = sku + 1;
    // Emit the appropriate event
    emit Baked(_upc);
  }
  

  // Define a function 'processtItem' that allows a farmer to mark an item 'Processed'
  function addCookieJarToOnlineStore(uint _upc)  public 
  // Call modifier to check if upc has passed previous supply chain stage
  
  baked(_upc)
  // Call modifier to verify caller of this function
  
          verifyCaller(items[_upc].originBakerID)

  {
    // Update the appropriate fields
    items[_upc].itemState = State.ForSale;
    // Emit the appropriate event
    emit ForSale(_upc);
  }

  // Define a function 'packItem' that allows a farmer to mark an item 'Packed'
  function buyCookieJar(uint _upc) public payable
  // Call modifier to check if upc has passed previous supply chain stage
  forSale(_upc)
    // Call modifer to check if buyer has paid enough
    paidEnough(items[_upc].productPrice)
    // Call modifer to send any excess ether back to buyer
    checkValue(_upc)
  // Call modifier to verify caller of this function
   onlyConsumer()
  {

        items[_upc].ownerID = msg.sender;
        items[_upc].consumerID = msg.sender;
        items[_upc].itemState = State.Sold; 
        // Transfer money to farmer
        items[_upc].originBakerID.transfer(items[_upc].productPrice);
        // emit the appropriate event
        emit Sold(_upc);

 
  }

  // Define a function 'sellItem' that allows a farmer to mark an item 'ForSale'
  function shipCookieJar(uint _upc,address _deliveryAgentID) public 
  // Call modifier to check if upc has passed previous supply chain stage
    sold(_upc)
 
  // Call modifier to verify caller of this function
            verifyCaller(items[_upc].originBakerID)

  {
    // Update the appropriate fields
        items[_upc].itemState = State.Shipped;
        items[_upc].deliveryAgentID = _deliveryAgentID;

    // Emit the appropriate event
        emit Shipped(_upc);

  }

  // Define a function 'buyItem' that allows the disributor to mark an item 'Sold'
  // Use the above defined modifiers to check if the item is available for sale, if the buyer has paid enough, 
  // and any excess ether sent is refunded back to the buyer
  function DeleverCookieJAr(uint _upc) public  
    // Call modifier to check if upc has passed previous supply chain stage
    shipped(_upc)
    // Call modifier to verify caller of this function
    onlyDeliveryAgent()
 
    {
    
    // Update the appropriate fields - ownerID, distributorID, itemState
    
    // Transfer money to farmer
            items[_upc].deliveryAgentID = msg.sender;

            items[_upc].itemState = State.Delivered;

    // emit the appropriate event
            emit Delivered(_upc);

  }

  

  // Define a function 'receiveItem' that allows the retailer to mark an item 'Received'
  // Use the above modifiers to check if the item is shipped
  function receiveItem(uint _upc) public 
    // Call modifier to check if upc has passed previous supply chain stage
    delivered(_upc)
    // Access Control List enforced by calling Smart Contract / DApp
    onlyConsumer()
    verifyCaller(items[_upc].consumerID)

    {
    // Update the appropriate fields - ownerID, retailerID, itemState
                items[_upc].itemState = State.Received;

    // Emit the appropriate event
                emit Received(_upc);

  }

   
  // Define a function 'fetchItemBufferOne' that fetches the data
  function fetchItemBufferOne(uint _upc) public view returns 
  (
  uint    itemSKU,
  uint    itemUPC,
  address ownerID,
  address originBakerID,
  string  originBakerName,
  string  originBakerInformation
   ) 
  {
  // Assign values to the 8 parameters
 
  itemSKU =   items[_upc].sku ;
   itemUPC  = items[_upc].upc;
  ownerID  = items[_upc].ownerID;
  originBakerID  = items[_upc].originBakerID;
  originBakerName  = items[_upc].originBakerName;
  originBakerInformation  = items[_upc].originBakerInformation;
   return 
  (
  itemSKU ,
  itemUPC,
  ownerID,
  originBakerID,
  originBakerName,
  originBakerInformation
   );
  }

  // Define a function 'fetchItemBufferTwo' that fetches the data
  function fetchItemBufferTwo(uint _upc) public view returns 
  (
  uint    itemSKU,
  uint    itemUPC,
  uint    productID,
  string  productNotes,
  uint    productPrice,
  uint    itemState,
  address deliveryAgentID,
   address consumerID
  ) 
  {

  itemSKU =   items[_upc].sku ;
  itemUPC  = items[_upc].upc;
  productID  = items[_upc].productID;
  productNotes  = items[_upc].productNotes;
  productPrice  = items[_upc].productPrice;
  itemState  = uint(items[_upc].itemState); 
  deliveryAgentID  = items[_upc].deliveryAgentID;
  consumerID  = items[_upc].consumerID;
    // Assign values to the 9 parameters
    
  return 
  (
  itemSKU,
  itemUPC,
  productID,
  productNotes,
  productPrice,
  itemState,
  deliveryAgentID,
  consumerID
  );
  }
}
